-- Daily ERP change log for order, salary and wallet mutations.
-- Both ERP apps share this Supabase project; apply this migration once.

create table if not exists public.erp_activity_logs (
  id bigint generated by default as identity primary key,
  organization_code text not null default 'shared',
  category text not null,
  table_name text not null,
  record_id text,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  summary text not null,
  actor_id text,
  old_data jsonb,
  new_data jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists erp_activity_logs_org_changed_idx
  on public.erp_activity_logs (organization_code, changed_at desc);
create index if not exists erp_activity_logs_category_changed_idx
  on public.erp_activity_logs (category, changed_at desc);

alter table public.erp_activity_logs enable row level security;
revoke all on public.erp_activity_logs from anon, authenticated;

create or replace function public.log_erp_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_old jsonb := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  v_new jsonb := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  v_row jsonb := coalesce(v_new, v_old, '{}'::jsonb);
  v_org text := 'shared';
  v_category text := coalesce(nullif(tg_argv[0], ''), 'system');
  v_record_id text;
  v_actor_id text;
  v_label text;
begin
  if tg_table_name like 'qiunai_%' then
    v_org := 'qiunai';
  elsif tg_table_name in ('orders', 'play_orders', 'players_bonus', 'salary_orders') then
    v_org := 'deepnight';
  end if;

  if v_row ? 'app_key' and v_row->>'app_key' in ('deepnight', 'qiunai') then
    v_org := v_row->>'app_key';
  elsif v_row ? 'organization_code' and v_row->>'organization_code' in ('deepnight', 'qiunai') then
    v_org := v_row->>'organization_code';
  end if;

  v_record_id := coalesce(
    v_row->>'order_no', v_row->>'order_id', v_row->>'id',
    v_row->>'user_id', v_row->>'discord_id'
  );
  v_actor_id := coalesce(
    v_row->>'edited_by', v_row->>'reviewed_by', v_row->>'approved_by',
    v_row->>'created_by', v_row->>'discord_id', v_row->>'user_id'
  );
  v_label := case tg_op
    when 'INSERT' then '新增'
    when 'UPDATE' then '更新'
    else '刪除'
  end;

  -- Skip updates that do not actually change row data.
  if tg_op = 'UPDATE' and v_old = v_new then
    return new;
  end if;

  insert into public.erp_activity_logs (
    organization_code, category, table_name, record_id, operation,
    summary, actor_id, old_data, new_data
  ) values (
    v_org, v_category, tg_table_name, v_record_id, tg_op,
    v_label || ' ' || tg_table_name || coalesce(' #' || v_record_id, ''),
    v_actor_id, v_old, v_new
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$function$;

do $block$
declare
  item record;
begin
  for item in
    select * from (values
      ('orders', 'order'),
      ('play_orders', 'order'),
      ('qiunai_orders', 'order'),
      ('qiunai_salary_orders', 'order'),
      ('salary_orders', 'order'),
      ('salary_wallet_entries', 'money'),
      ('salary_withdraw_requests', 'money'),
      ('salary_requests', 'money'),
      ('players_bonus', 'money'),
      ('qiunai_staff_bonus', 'money'),
      ('users', 'money'),
      ('wallet_logs', 'money'),
      ('monthly_bills', 'money'),
      ('accounting_ledger_entries', 'money')
    ) as targets(table_name, category)
  loop
    if to_regclass('public.' || item.table_name) is not null then
      execute format('drop trigger if exists erp_activity_log_trigger on public.%I', item.table_name);
      execute format(
        'create trigger erp_activity_log_trigger after insert or update or delete on public.%I for each row execute function public.log_erp_activity(%L)',
        item.table_name,
        item.category
      );
    end if;
  end loop;
end;
$block$;

notify pgrst, 'reload schema';
